version: "3.9"
services:
  web:
    build: .
    environment:
      - TZ=Asia/Kolkata
    command : bash -c "python3 load_test.py"
    networks:
      - my-network
    restart: on-failure

networks:
  my-network:
    external: true